#########################
# Docker compose rtools #
#########################
version: '3.9'

services:
    rtools:
        image: rtools:1.0
        build:
            context: ./
            dockerfile: rtools_dockerfile
        entrypoint: [ "/bin/bash", "-l", "-c" ]
        container_name: rtools
        restart: "no"
        command: "'while true; do sleep 60; done'"
        volumes:
            - /home1/data/STARK/output/repository:/output/repository:rw
            - /home1/BAS/lavauxt/input:/input
            - /home1/data/STARK/databases:/databases:rw
